name: truekapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  provider: ^6.1.2
  sizer: ^2.0.15
  google_fonts: 6.3.2
  lottie: ^3.1.0
  shared_preferences: ^2.1.1
  geolocator: ^14.0.2
  image_picker: ^1.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geocoding: ^2.1.2
  intl: ^0.20.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/